### ISSUE TITLE
[Feature RQ]: Customization for Lighting Properties for the Render command

### ISSUE THREAD

**Issue by cens6r** [bedev2/Grid-Bot-Issues#7]
**Describe the feature you'd like implemented**
Ability to customize the PointLights properties for the render command with new params

**How could this feature improve the grid?**
This feature can improve grid because its cool and epic and seems like a neat addition

**Additional context**
make the color use rgb code plzzzzzz and also let us customize other properties like brightness, range, shadows etc

**Comment by 3UR** [comment]
Implemented into debug, will be pushed to production soon.

# Details about implementation
1. Currently the parameters only affect 'usercloseup'
2. The values like 'Brightness' and 'Color3red' have a maximum length of : Brightness=100, Color=255

**Comment by 3UR** [comment]
Closing as completed.
